### ISSUE TITLE
problem with the latest version 25/4/2015 

### ISSUE THREAD

**Issue by akram1** [slmoebius/builder#10]
I have 3 problems whith uninstalling builder, installing builder and creating new module
(Python 2.7.8, PostgreSQL 9.4.1)

I tired to reinstall module builder but failed to uninstall. It stops at 
openerp.addons.base.ir.ir_model: Dropped FK CONSTRAINT builder_ir_module_module_import_local_wizard_write_uid_fkey@builder.ir.module.module.import.local.wizard

Postgres Error
STATEMENT:  ALTER TABLE "builder_ir_model_fields" ADD CONSTRAINT "builder_ir_model_fields_size_gt_zero" CHECK (size>=0)
LOG:  unexpected EOF on client connection with an open transaction
LOG:  unexpected EOF on client connection with an open transaction
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  operator does not exist: character varying >= integer
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  ALTER TABLE "builder_ir_model_fields" ADD CONSTRAINT "builder_ir_model_fields_size_gt_zero" CHECK (size>=0)
ERROR:  operator does not exist: character varying >= integer
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  ALTER TABLE "builder_ir_model_fields" ADD CONSTRAINT "builder_ir_model_fields_size_gt_zero" CHECK (size>=0)
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT
ERROR:  could not obtain lock on row in relation "ir_cron"
STATEMENT:  SELECT *
	                                   FROM ir_cron
	                                   WHERE numbercall != 0
	                                      AND active
	                                      AND nextcall <= (now() at time zone 'UTC')
	                                      AND id=1
	                                   FOR UPDATE NOWAIT

##############################################################
I tired to install module builder in a newly created database. It went fine but Odoo raised the following errors:

2015-04-25 21:57:07,892 13310 ERROR 8-1 openerp.sql_db: Programming error: operator does not exist: character varying >= integer
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
, in query ALTER TABLE "builder_ir_model_fields" ADD CONSTRAINT "builder_ir_model_fields_size_gt_zero" CHECK (size>=0)
2015-04-25 21:57:07,892 13310 WARNING 8-1 openerp.models.schema: Table 'builder_ir_model_fields': unable to add 'CHECK (size>=0)' constraint !
 If you want to have it, you should update the records and execute manually:
ALTER TABLE "builder_ir_model_fields" ADD CONSTRAINT "builder_ir_model_fields_size_gt_zero" CHECK (size>=0)
2015-04-25 21:57:15,607 13310 ERROR 8-1 openerp.models: The column parent_id on object builder.ir.ui.menu must be set as ondelete='cascade' or 'restrict'

2015-04-25 21:57:34,517 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,539 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,562 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,588 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,610 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,632 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,656 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,678 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,701 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,725 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,748 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,782 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.
2015-04-25 21:57:34,807 13310 ERROR 8-1 openerp.tools.yaml_import: You have an empty block in your tests.

###################################################################
I couldn't create a module it throw an error:

Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4231, in _create
    recs.modified(self._fields)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 5627, in modified
    spec += self._fields[fname].modified(self)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/fields.py", line 1479, in modified
    spec = super(_Relational, self).modified(records)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/fields.py", line 960, in modified
    target = env[field.model_name].search([(path, 'in', records.ids)])
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4621, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4444, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/osv/expression.py", line 827, in parse
    elif len(path) > 1 and column._type == 'many2one' and column._auto_join:
AttributeError: 'NoneType' object has no attribute '_type'

**Comment by akram1** [comment]
The problem remains the same after the update. I even created new database and install builder as the first app.

**Comment by akram1** [comment]
2015-05-09 20:05:33,010 26277 ERROR 8-1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4231, in _create
    recs.modified(self._fields)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 5627, in modified
    spec += self._fields[fname].modified(self)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/fields.py", line 1479, in modified
    spec = super(_Relational, self).modified(records)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/fields.py", line 960, in modified
    target = env[field.model_name].search([(path, 'in', records.ids)])
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4621, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4444, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/osv/expression.py", line 827, in parse
    elif len(path) > 1 and column._type == 'many2one' and column._auto_join:
AttributeError: 'NoneType' object has no attribute '_type'

**Comment by ahm507** [comment]
I have the same problem:

....

/odoo/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/Users/Macpro/Projects/JudicialWF/odoo/openerp/osv/expression.py", line 827, in parse
    elif len(path) > 1 and column._type == 'many2one' and column._auto_join:
AttributeError: 'NoneType' object has no attribute '_type'
