### ISSUE TITLE
Fail to install module

### ISSUE THREAD

**Issue by effelle** [slmoebius/builder#11]
Odoo V8, here.
I added the builder (04/25) module to my addons folder and run an update module list in oddo. Here the result:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 393, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 397, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/opt/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/opt/odoo/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/addons/builder-master/__init__.py", line 3, in <module>
    from . import models
  File "/opt/odoo/addons/builder-master/models/__init__.py", line 5, in <module>
    from . import module
  File "/opt/odoo/addons/builder-master/models/module.py", line 14, in <module>
    from openerp.addons.builder.tools import simple_selection
  File "/opt/odoo/openerp/modules/module.py", line 79, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named builder

When force import with the Base import module I get missing dependencies:

Error while importing module 'builder-master': "(u'Error !', u'Unmet module dependencies: web_ace_editor, generic_document_render_jinja')"

F.

**Comment by onemoverx** [comment]
yes, all dependencies you can find it in our github account specifically https://github.com/slmoebius/generic_document_render, https://github.com/slmoebius/generic_document_render_jinja and https://github.com/slmoebius/web_ace_editor

**Comment by effelle** [comment]
Strabge, I didn't see the list of dependencies here on github. Anyway, still not working:
I've installed web_ace_editor (no errors) but when I tried to install generic_document_render-master I got the error
"You try to install module 'generic_document_render-master' that depends on module 'web_ace_editor'.
But the latter module is not available in your system." A restart of odoo server (and a reboot of the system) didn't resolve he issue.

**Comment by onemoverx** [comment]
I think that you must change the folder name, the right name for the module is generic_document_render (github add the "-master" part when not in a folder). The same applies to all other dependencies. Shortly will be no module dependencies and will be much more easy to install, We'll think about putting all inside a folder to avoid those errors in the future.

**Comment by effelle** [comment]
Yes. Pulling out '-master' for every modules resolved the issue. Thanks.
