### ISSUE TITLE
Error on UML diagram

### ISSUE THREAD

**Issue by akram1** [slmoebius/builder#4]
I installed 'builder' on latest Odoo8 Linux 64bit Python 2.7.8. I created a simple module successfully after creating a module a tried to edit though UML Diagram and a got this error

Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web_diagram/controllers/main.py", line 35, in get_diagram_info
    (140, 180), req.session.context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo/addons/odoo8/builder/tools/graph.py", line 244, in graph_get
    transitions.append((a['id'], t[des_node][0]))
TypeError: 'bool' object has no attribute '__getitem__'

**Comment by onemoverx** [comment]
the new update must resolve this issue. confirm it please

**Comment by onemoverx** [comment]
A new module for improvement of web_diagram was published to allow saving the position of the nodes (models) that gives a level of clarification to the diagram. Hope it helps!
